### PR TITLE
Display file sizes

### PR DESCRIPTION
**Pull request by neunenak**
Display the file size of files in the listing.

### CODE REVIEW

**Comment by casey** [comment]
@soenkehahn This looks good to me, so please take a look when you get the chance.

This displays file sizes on the right-hand side of listings. We used the `humantime` library, which isn't great, but seemed better than rolling our own byte formatting.

**Comment by SachinMeier** [comment]
I'm not very familiar with Rust, but I ran this branch locally, servings several different file types, downloaded files, and didn't see any bugs. With some MP3 files, the sizes calculated by MacOS differed from the size displayed on agora.

**Comment by neunenak** [comment]
> I'm not very familiar with Rust, but I ran this branch locally, servings several different file types, downloaded files, and didn't see any bugs. With some MP3 files, the sizes calculated by MacOS differed from the size displayed on agora.

This PR uses this rust std library method: https://doc.rust-lang.org/std/fs/struct.Metadata.html#method.len to calculate the file size. This is different than the space of blocks on the non-volatile storage taken up by the file, which is what desktop OSs might be reporting.

**Comment by casey** [comment]
Merged in master, and moved tests to `src/integration.rs`, where such tests should now live.

I think `humantime` is a bit weird, and want to replace it, but I don't think that should hold up this diff, so merging.

**Pull request merged**
