### PR TITLE
Use integration tests instead of unit tests

### PR DESCRIPTION
**Pull request by casey**
Test count on master before this PR:

115 unit tests
2 status tests
3 integration tests
120 total

### CODE REVIEW

**Comment by casey** [comment]
@soenkehahn and I agreed that it would probably be good to clean this up and merge it, so that it doesn't block other things. I reverted the last couple commits. One moved a test but was still failing, and I didn't want to block merging on fixing it. The other one was passing, but would be hard to clean up.

**Comment by casey** [comment]
I did some minor cleanup, and gave the code a once over, and I think this is ready to go. Take a look and feel free to merge.

**Comment by casey** [comment]
@soenkehahn I did some minor cleanup, and gave the code a once over, and I think this is ready to go. Take a look and feel free to merge.

**Comment by soenkehahn** [comment]
For some reason the tests from this branch sometimes don't terminate on my machine. A bunch of `chromium` processes are taking up a lot of CPU when that happens. This is the test that's hanging: `tests::browser_tests::copy_payment_request_to_clipboard`.

**Comment by casey** [comment]
Just to confirm, this doesn't happen on `master`? Reviewing the PR, I can't spot anything that's changed. Is it possible that something changed w.r.t. the version of chrome you have installed, or clipboard preferences?

**Comment by soenkehahn** [comment]
Good question. After checking again, I can reproduce the bug also on master. :( I'll open a ticket.

**Comment by casey** [comment]
Let me know what you think of the PR too, although I can definitely work on top of it for now.

**Comment by soenkehahn** [comment]
Yeah, I'll try to review it soon!

**Pull request merged**
